
url: http://sunyazhou13.github.io
title: Asia Sun
subtitle: 技术要求我们不断学习,与时俱进, 来迎接未来未知的挑战.
author: sunyazhou13
simple_search: http://google.com/search

description: 能解决的问题尽量别吵吵

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: sunyazhou13@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 5          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
<<<<<<< HEAD
# default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
=======
default_asides: []
>>>>>>> a4ca3b5541d2087c6529414842ec04c09b37e4a2

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: sunyazhou13
github_repo_count: 3
github_show_profile_link: false
github_skip_forks: true

<<<<<<< HEAD
# Twitter
# twitter_user:
# twitter_tweet_button: true
=======
>>>>>>> a4ca3b5541d2087c6529414842ec04c09b37e4a2

# Google +1
# google_plus_one: false
# google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
# googleplus_user:
# googleplus_hidden: false

# Pinboard
# pinboard_user:
# pinboard_count: 3

# Delicious
# delicious_user:
# delicious_count: 3

# Disqus Comments
disqus_short_name: studentdeng
disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id:

<<<<<<< HEAD
# Facebook Like
# facebook_like: false
=======
# weibo_share
weibo_share: true

# duoshuo comments
duoshuo_comments: true
duoshuo_short_name: sunyazhou13

duoshuo_asides_num: 5      # 侧边栏评论显示条目数
duoshuo_asides_avatars: 0   # 侧边栏评论是否显示头像
duoshuo_asides_time: 0      # 侧边栏评论是否显示时间
duoshuo_asides_title: 0     # 侧边栏评论是否显示标题
duoshuo_asides_admin: 0     # 侧边栏评论是否显示作者评论
duoshuo_asides_length: 18   # 侧边栏评论截取的长度

# Greyshade theme config
weibo_user: sunyazhou13 # 微博数字 ID 或域名 ID
dribbble_user: curer
weibo_share: true # 是否开启微博分享按钮
>>>>>>> a4ca3b5541d2087c6529414842ec04c09b37e4a2
